TEXT_GAMEOVER = "RESULTADOS";
TEXT_OF = "/";
TEXT_SCORE = "PUNTOS";
TEXT_BEST_SCORE = "MEJOR PUNTAJE";
TEXT_MULTIPLIER = "x";
TEXT_ARE_SURE = "¿ESTÁS SEGURO?";
TEXT_BALL_OUT = "FUERA";
TEXT_PAUSE = "PAUSA";
TEXT_CONGRATULATION = ["¡BIEN!", "¡GENIAL!", "¡EXCELENTE!"];
TEXT_SAVED = "ATAJADA";
TEXT_HELP = "DESLIZA LA PELOTA / DESLIZE A BOLA";
TEXT_DEVELOPED = "DESARROLLADO POR";
var TEXT_PRELOADER_CONTINUE = "JUEGA";


TEXT_SHARE_IMAGE = "200x200.jpg";
TEXT_SHARE_TITLE = "Felicitaciones!";
TEXT_SHARE_MSG1 = "Lograste <strong>";
TEXT_SHARE_MSG2 = " puntos</strong>!<br><br>Comprate tu puntaje!";
TEXT_SHARE_SHARE1 = "Obtuve ";
TEXT_SHARE_SHARE2 = " puntos! ¿Puedes hacerlo mejor?";
TEXT_SHARE_SHARE3 = "Felicitaciones";
TEXT_SHARE_SHARE4 = "SigueIntentando";